name: propertio_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^5.1.0
  dartz: ^0.10.1
  connectivity_plus: ^4.0.2
  flutter_secure_storage: ^9.0.0
  carousel_slider: ^4.2.1
  toggle_switch: ^2.1.0
  url_launcher: ^6.2.1
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  share_plus: ^7.2.2
  flutter_svg: ^2.0.9
  another_flushbar: ^1.12.30
  shimmer: ^2.0.0
  flutter_widget_from_html: ^0.10.6
  awesome_dialog: ^3.2.0
  webview_flutter: ^4.0.0
  currency_text_input_formatter: ^2.1.13
  package_info_plus: ^5.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

